# Generated by Django 3.1 on 2021-06-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210618_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='description',
            new_name='description_o',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='name_o',
        ),
    ]
